#!/bin/bash
#PBS -S /bin/bash
#PBS -N run_real_namibia
#PBS -l nodes=1:ppn=64
#PBS -m abe
#PBS -M William.Capehart@sdsmt.edu


cd /home/wcapehart/WRFV381_TKE/WRFV381/WRFV3/test/em_real
export OMP_NUM_THREADS=64

echo Begin WRF Run
rm -frv ./nodeinuse.txt ./wrf.log ./wrfout*
rm -frv ./wrfrst*
rm -frv  ./rsl* ./K???.d?.??
uname -a
uname -a >& ./nodeinuse.txt
date -u
mpirun  -np 64 ./real.exe
echo End WRF Run
date -u
exit 0
