#!/bin/bash
#PBS -S /bin/bash
#PBS -N run_real_namibia
#PBS -l nodes=1:ppn=64
#PBS -m abe
#PBS -M William.Capehart@sdsmt.edu
source ~/bin/loadpackage.sh openmpi 


cd /home/wcapehart/WRFV381_TKE/WRFV381/WRFV3/test/em_real
export OMP_NUM_THREADS=64


echo
echo =======================================================
echo
echo REAL Began at `date -u`
echo
echo =======================================================
echo

echo Begin REAL Run
rm -frv ./nodeinuse.txt ./wrf.log ./wrfout*
rm -frv ./wrfrst*
rm -frv  ./rsl* ./K???.d?.??
uname -a
uname -a >& ./nodeinuse.txt
date -u
##  nohup mpirun  -np 64 ./real.exe
nohup ./real.exe >& ./real.log 
echo End REAL Run
date -u
date -u > /home/wcapehart/WRFV381_TKE/WRFV381/WRFV3/test/em_real/my_real_is_done.txt


echo
echo =======================================================
echo
echo REAL Ends at `date -u`
echo
echo =======================================================
echo



exit 0
